### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by HanYuanyuaner** [neuleaf/MobileNetV2#11]
(python35) hyuan@Host49:~/model/MobileNetV2$ python train_mobilenetv2.py --epoch 1 --dataset_dir ./dataset_tools/tfrecords --n_class 8 --batch_size 4 --num_samples 20
Traceback (most recent call last):
  File "train_mobilenetv2.py", line 3, in <module>
    from config import *
  File "/home/nishome/hyuan/model/MobileNetV2/config.py", line 34, in <module>
    args = parser.parse_args()
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 1729, in parse_args
    self.error(msg % ' '.join(argv))
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 2383, in error
    self.print_usage(_sys.stderr)
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 2353, in print_usage
    self._print_message(self.format_usage(), file)
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 2319, in format_usage
    return formatter.format_help()
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 278, in format_help
    help = self._root_section.format_help()
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 208, in format_help
    func(*args)
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 316, in _format_usage
    action_usage = format(optionals + positionals, groups)
  File "/home/nishome/hyuan/anaconda3/envs/python35/lib/python3.5/argparse.py", line 387, in _format_actions_usage
    start = actions.index(group._group_actions[0])
IndexError: list index out of range
 
Did anyone meet this problem?

**Comment by LQNew** [comment]
hello, I have met this problem, because in config.py, "n_class" doesn't exist, so you can change "n_class" to "num_classes", this problem will be solved.

**Comment by neuleaf** [comment]
@LQNew you are right. Thanks for share.
