### ISSUE TITLE
when I use this code to classify multi-objects,many bugs detected?so do you really use this code to try pacvoc?

### ISSUE THREAD

**Issue by BlueBubbleWei** [neuleaf/MobileNetV2#12]
Traceback (most recent call last):
  File "E:/自己的项目/MobileNetV2/train_mobilenetv2.py", line 118, in <module>
    main()
  File "E:/自己的项目/MobileNetV2/train_mobilenetv2.py", line 37, in main
    img_batch, label_batch = get_batch(filename_queue, args.batch_size)
  File "E:\自己的项目\MobileNetV2\utils.py", line 89, in get_batch
    input_queue = tf.train.slice_input_producer([image, label], shuffle=False)
  File "D:\python3\lib\site-packages\tensorflow\python\training\input.py", line 340, in slice_input_producer
    output = [array_ops.gather(t, index) for t in tensor_list]
  File "D:\python3\lib\site-packages\tensorflow\python\training\input.py", line 340, in <listcomp>
    output = [array_ops.gather(t, index) for t in tensor_list]
  File "D:\python3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2585, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "D:\python3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 2334, in gather
    validate_indices=validate_indices, name=name)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "D:\python3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be at least rank 1 but is rank 0 for 'input_producer_1/Gather_1' (op: 'Gather') with input shapes: [], [].

the path  is correct,but i still can't read the data,wait for your reply,thank you1

**Comment by neuleaf** [comment]
抱歉，训练部分的代码可能有问题。该部分不再更新，建议参考官方代码，有问题可以留言
