### ISSUE TITLE
NameError: name 'bytes_feature' is not defined

### ISSUE THREAD

**Issue by xiaoluojun** [neuleaf/MobileNetV2#16]
Traceback (most recent call last):
  File "convert2tf.py", line 66, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "convert2tf.py", line 59, in main
    example=convert2example(FLAGS.img_dir, line)
  File "convert2tf.py", line 38, in convert2example
    'image/encoded': bytes_feature(image_data),
NameError: name 'bytes_feature' is not defined
感谢分享，应该是tensorflow版本的问题，请问作者使用的是tensorflow的哪个版本？

**Comment by neuleaf** [comment]
抱歉。这个项目应该使用的是1.5的版本。这代码不建议使用了。有需要可以去参考官方的models。
